### ISSUE TITLE
GPU Speed & Temperature Monitoring

### ISSUE THREAD

**Issue by downfall24** [sebhildebrandt/systeminformation#111]
### Issue Type

* [x] Feature Request

This is a great library, so thanks, for what I'm building I could really do with getting more in-depth GPU information such as the speed and the core temperature, is this something on your road map? I'm happy to help out bringing this information to your library if it is.

**Comment by sebhildebrandt** [comment]
Hi @downfall24,
Thank you for your request. Getting detailed GPU information would be really fine but it turns out that this is highly dependent on type/vendor of graphics card and will result in a number of dependencies. At least I didn't found reliable ways to get more detailed information (across platforms) yet. This is the current status.

But if you have any ideas or can point to sources for solutions for this request, I would be happy to implement that.
