### ISSUE TITLE
getDynamicData doesn't work under Alpine Linux

### ISSUE THREAD

**Issue by dmitryt** [sebhildebrandt/systeminformation#121]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 
Package shouldn't be crashed in such situation;

### Actual behavior
Package is crashed in such situation;

### Steps to reproduce the problem
```
> var si = require('systeminformation');
undefined
> si.getDynamicData(function(data) {console.log(data)})
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events:
      { removeListener: [Function: updateExceptionCapture],
        newListener: [Function: updateExceptionCapture],
        error: [Function: debugDomainError] },
     _eventsCount: 3,
     _maxListeners: undefined,
     members: [] } }
> TypeError: Cannot read property 'to' of undefined
    at checkColumn (/application/src/server-koa/node_modules/systeminformation/lib/processes.js:255:46)
    at parseLine (/application/src/server-koa/node_modules/systeminformation/lib/processes.js:266:5)
    at /application/src/server-koa/node_modules/systeminformation/lib/processes.js:312:23
    at Array.forEach (<anonymous>)
    at parseProcesses (/application/src/server-koa/node_modules/systeminformation/lib/processes.js:310:13)
```
Actually the same code works fine under OSX. So, I assume, this might be a platform related issue.

### Specifications 

- package version: 3.37.8
- operating system: Alpine Linux 3.6.2
- hardware:

**Comment by sebhildebrandt** [comment]
@dmitryt : Can you provide the output of the following commands?

```
ps axo pid:10,pcpu:6,pmem:6,pri:5,vsz:10,rss:10,ni:5,start:20,state:20,tty:20,user:20,command
```

and

```
ps axo pid,pcpu,pmem,pri,vsz,rss,ni,start,state,tty,user,command
```

I guess there is a slightly different formatting which causes the problem ...

Thank you in advance ...

**Comment by dmitryt** [comment]
```
$ ps axo pid:10,pcpu:6,pmem:6,pri:5,vsz:10,rss:10,ni:5,start:20,state:20,tty:20,user:20,command
PID   USER     TIME   COMMAND
    1 root       0:00 npm
   16 root       0:00 sh -c node index.js "|" "tee" "/var/log/gdn-ui/gdn-middletier.log"
   17 root       0:01 node index.js | tee /var/log/gdn-ui/gdn-middletier.log
   23 root       0:12 /usr/local/bin/node /application/src/server-koa/index.js | tee /var/log/gdn-ui/gdn-middletier.log
   33 root       0:00 /bin/sh
   40 root       0:00 /bin/sh
   46 root       0:00 ps axo pid:10,pcpu:6,pmem:6,pri:5,vsz:10,rss:10,ni:5,start:20,state:20,tty:20,user:20,command
```
```
$ ps axo pid,pcpu,pmem,pri,vsz,rss,ni,start,state,tty,user,command
PID   USER     TIME   COMMAND
    1 root       0:00 npm
   16 root       0:00 sh -c node index.js "|" "tee" "/var/log/gdn-ui/gdn-middletier.log"
   17 root       0:01 node index.js | tee /var/log/gdn-ui/gdn-middletier.log
   23 root       0:12 /usr/local/bin/node /application/src/server-koa/index.js | tee /var/log/gdn-ui/gdn-middletier.log
   33 root       0:00 /bin/sh
   40 root       0:00 /bin/sh
   47 root       0:00 ps axo pid,pcpu,pmem,pri,vsz,rss,ni,start,state,tty,user,command
```

**Comment by sebhildebrandt** [comment]
Hi @dmitryt 
Think you for providing the results of the commands ... I am also no able to test it here using node:alpine container. 

The problem is in `processes()`, where the `ps` command does not returns the expected values. I will add a fix for that. As I also see, inside alpine docker container, the processes() function will then not return all data as on a bare metal machine. Anyway, the `getDynamicData()` should then work without any error again. I will provide a fix beginning next week.

**Comment by sebhildebrandt** [comment]
Fixed. New version 3.37.9 released.

**Comment by cigzigwon** [comment]
In alpine world you also should make sure that [procps](https://gitlab.com/procps-ng/procps) is installed or busybox. I found that busybox has issues w/gtop

**Comment by cigzigwon** [comment]
The last issue would be in the disk information. In Alpine world there is no option -l to filter to the local filesystem so I suspect this is also the issue for gtop when the disk usage pane has nothing in it yet the raw command of df -lkPT produces an error. I'm not sure how you would go about handling this case after looking at the code because you would need to check 'Alpine' someplace and also refactor so that you have a Factory so you don't have all of the inline if statements for each OS.

**Comment by sebhildebrandt** [comment]
@cigzigwon I will have a look on that. Thank you for pointing to this issue.

**Comment by sebhildebrandt** [comment]
@cigzigwon for the `fsSize()` I guess I have a solution. But for your first comment, I do not really get the point. Not sure, you mentioned `gtop`which I am not using ...

**Comment by cigzigwon** [comment]
Since this lib is a dependancy of gtop which I am using in Alpine with Node Ive noted why it is important to have underlying libs to support your lib which fixes gtop. So with that being said you at least need Alpine procps OR busybox and coretools packages installed for the OS.

**Comment by sebhildebrandt** [comment]
@cigzigwon ... ok, clear. So now the question would be, when/how to check it ... 

- I guess with app list I could check if the packages are installed
- then the question remains WHEN to check it ...

If I am pulling a alpine docker container, busybox is already installed so there `systemInformation` works out of the box. Never tried alpine on a bare metal ...

**Comment by cigzigwon** [comment]
I was just mentioning that busybox is not installed in certain builds, like the ones for node. In my case it is 'node:carbon-alpine'. I don't know that it actually needs to check for the install now because by simply installing the package 'coreutils' you will get the GNU version of df which includes -l. So I think at this point leaving things alone might be best. I ended up here because of using these node builds. I'm thinking when you pull a vanilla Alpine box you would have both busybox and coreutils packages available. I'm not sure what version of df I was using before that since there was no -l option available it was triggering error case in that method.

**Comment by sebhildebrandt** [comment]
@cigzigwon ahh, ok. I anyway have now a fallback for the -l problem ... already published in the latest version.

**Comment by cigzigwon** [comment]
@sebhildebrandt Well that was fast. Many times I hit the fast track with these docker images which are good for app dev and then I try to utilize them later for diag. I can now monitor CoreOS and RancherOS nodes with ease using gtop. Thanks for your great contribution!
