### ISSUE TITLE
Information availability within a docker container

### ISSUE THREAD

**Issue by funkyfisch** [sebhildebrandt/systeminformation#122]
### Issue Type

* [ ] Bug
* [ x ] Feature Request
* [ ] Question

### Expected behavior 
si.bios() and si.system() should return at least some fields with data

### Actual behavior
the above functions return nothing, when run on a nodejs app within a docker container.
Tested on a x64 ubuntu 16.04 and raspbian-stretch on a Pi3

### Steps to reproduce the problem
Run a simple nodejs app with si imported, within a docker container

### Specifications 

- package version: newest
- operating system: ubuntu 16.04 & raspbian jessie
- hardware: dell inspiron && raspberry pi 3

### Problem and possible solution

I might be doing something wrong here. There are functions that return true information (such as current load and cpu info) and some that return strange info ( si.batteryInfo() returns that my laptop is 167.9 percent charged and thinks it is unplugged even if I have it plugged in to mains)
It is my first issue on github so please be easy on me!
Thank you

**Comment by sebhildebrandt** [comment]
Hi @funkyfisch 
as Docker provides isolated environments (with own security context), it is not possible to access to all information of the hosting system. This limitation by design so therefor you will only get partial information from within a docker container. Especially bios and system will not work like directly from the hosting machine.

One more thing: The battery information you got: was this from within docker or from outside? Can you provide all exact outputs that are strange + describe if this is from inside a docker container or not? Thank you in advance.

**Comment by funkyfisch** [comment]
@sebhildebrandt Thanks for the quick reply, I am grateful! 
I was ignorant about these intricacies of Docker.

All information I ever fetched with the si library was done from within a container. I can work on running all available calls in your library at some point from a container running on my laptop running Ubuntu 16 and dump them maybe here? 
At the moment actually it seems to be showing correct data ( my battery was discharged during the day and now I plugged in - running the container now it shows 34 percent and i have this returned 
`"hasbattery":true,"cyclecount":0,"ischarging":true,"maxcapacity":5144000,"currentcapacity":1781000,"percent":34.62286158631415`
