### ISSUE TITLE
Hard drive SMART data?

### ISSUE THREAD

**Issue by tankerkiller125** [sebhildebrandt/systeminformation#137]
### Issue Type

* [ ] Bug
* [X] Feature Request
* [ ] Question

### Expected behavior 

It would be awesome if this project could collect the SMART data from hard drives. I'm currently using this project in a custom remote monitoring system for endpoint PCs and at the moment the only hard drive related warning I have set is for running out of space. I would really love it if I could also set it up for SMART errors/messages.

### Specifications 

- operating system: Linux, Mac, Windows
- hardware: Any

**Comment by sebhildebrandt** [comment]
Hi @tankerkiller125 , I also would like to see that in this package. Unfortunately I did not found a reliable way to get smart status without certain dependencies. But I will try to find a smart way to retrieve S.M.A.R.T. status when needed libraries are installed.

**Comment by mpathy** [comment]
Proper S.M.A.R.T. detection always needs the smartmontools, so you
They are available on all systems.

In the end its the same as with the temperature settings.

For most people it will be okay if they get what they get - and are able to get more information like temperature or SMART data when installing additional software.

If you like to tinker around with some C library and the node addon interface or what it is called, you could take a look at this here: http://git.0pointer.net/libatasmart.git/tree/

But otherwise I would just do some "retrieve values if smartmontools are installed, otherwise ignore". For retrieving the values, you could take a look at pySMART, how they did it: https://pypi.org/project/pySMART/#description

But yes, overall +1 from me, would be very cool

**Comment by sebhildebrandt** [comment]
@mpathy - you are absolutely right! Will have a look on it.

**Comment by tankerkiller125** [comment]
@mpathy the only problem I find with this solution is windows and Mac support, both are very important where I work and it seems that smartmontools isn't a thing for windows.

**Comment by mpathy** [comment]
@tankerkiller125 It is available for every system: https://www.smartmontools.org/wiki/Download#InstalltheWindowspackage

**Comment by tankerkiller125** [comment]
@mpathy In that case ignore what I said, I'm all for this solution then.

**Comment by sebhildebrandt** [comment]
Just published a new version which supports detecting SMART status (`diskLayout() --> [...].smartStatus`). Be sure to install `smartmontools` if you are running on linux. See version 3.45.0
