### ISSUE TITLE
Doesnt ryzen work?

### ISSUE THREAD

**Issue by lordjbs** [sebhildebrandt/systeminformation#190]
### Issue Type

* [ ] Bug
* [ ] Feature 
* [X] Question

I am trying to read the CPU Temperatures. I just get -1°C which is not really possible.
![grafik](https://user-images.githubusercontent.com/23281889/50724940-f847d580-10f5-11e9-8385-e98b8f525943.png)

Is there anything against this?

I did this command from some issue. Its german, and it says not supported.
![grafik](https://user-images.githubusercontent.com/23281889/50724925-c0409280-10f5-11e9-8265-3e570283c533.png)

### Specifications 

- package version: 3.54.0
- operating system: Win 10 Pro
- hardware: AMD Ryzen 2 2600X

**Comment by sebhildebrandt** [comment]
@lordjbs: as mentioned in the README:

**Windows Temperature, Battery, ...**

`wmic` - which is used to determine temperature and battery sometimes needs to be run with admin privileges. So if you do not get any values, try to run it again with according privileges. If you still do not get any values, your system might not support this feature. In some cases we also discovered that `wmic` returned incorrect temperature values.

So this is not really related to ryzen as this happens also on other windows systems ...

**Comment by EnKrypt** [comment]
It may not be *specific* to Ryzen, but it definitely does seem to be affecting all Ryzen systems consistently. 

Most likely the case is that the stock method to check temps on Windows does not work on these chips, which is likely given that most software and tools to check temperatures as you would on Intel do not work on Ryzen (realtemp, coretemp, etc).

The only reliable way is to read from the hardware sensor using a monitoring tool like HWInfo or HWMonitor. Since `wmic` is not aware of this difference, it just straight up doesn't handle it.

That sucks, but I guess we should look at an alternate way to measure temps on Windows.
