### ISSUE TITLE
Strange cpu frequency / temp on Windows 10

### ISSUE THREAD

**Issue by Elyspio** [sebhildebrandt/systeminformation#218]
**Describe the bug**
On Windows, data gotten by method cpuCurrentSpeed, cpuTemperature seem not correct: my processor is overclocked to 4.6 GHz (checked in task manager) but modules get me back strange data.

Also I tried to check directly with wmic (as I know, this module get data from it) and it's the same value (4.01 instead of 4.6).

I run the app with _administrator privileges_.
 
But on Linux everything works

**To Reproduce**
Just call cpuCurrentSpeed and cpuTemperature on windows

**Current Output**
from si.cpuCurrentSpeed()
- avg: 4.01
- cores:  [
    - 0: 4.01
    - 1: 4.01
    - 2: 4.01
    - 3: 4.01
    - 4: 4.01
    - 5: 4.01
    - 6: 4.01
    - 7: 4.01
]
- max: 4.01
- min: 4.01

from si.cpuTemperature(): 
+ cores: [
    - 0: 27.8
    - 1: 29.8
]
+ main: 28.8
+ max: 29.8

**Expected behavior**
Get the correct values for cpu's frequency and the good number of cores from cpuTemperature()
![Taskmgr_2019-04-22_12-26-18](https://user-images.githubusercontent.com/22132082/56496489-ec8feb80-64f9-11e9-8cd0-ad18bcaa5247.png)

**Environment (please complete the following information):**
 - systeminformation package version: lastest (4.1.5)
 - OS: Windows 10 
 - Hardware Intel core I7 6700K overclocked and fixed to 4.6 GHz

thanks you for reading :).

**Comment by Leigham** [comment]
mines doing the same thing, showing base speeds instead of actual speed, its the same issue with `os.cpus`

**Comment by Leigham** [comment]
looked into how you fetch the speeds, and its wmic that is not returning the right details.
![image](https://user-images.githubusercontent.com/8463408/57129113-61321800-6d8d-11e9-80ae-646ba5084fb6.png)

**Comment by nrpatten** [comment]
Could this issue be because of `Intel Speed Step`, If you look at your screen cap @Elyspio you will see `Base Speed` is set at `4.0 GHz`. in your bios `EIST = Intel SpeedStep` 

My Ryzen CPU has the AMD version disabled in the bios..
![Untitled](https://user-images.githubusercontent.com/4833541/58747089-88255c00-84a9-11e9-89c7-88f6991e805c.jpg)

**Comment by CodeF0x** [comment]
Is there any update on this? I'm having the same issue, both on Windows 10 and MacOS Mojave. Both times it only shows the base clock, but not the actual speed.

**Comment by sebhildebrandt** [comment]
@CodeF0x, @Elyspio, @Leigham ... as `wmic` (windows) as well as `os.cpus` (Mac OS) do not return actual frequencies, the only way to get the current frequency would be to include platform specific `c` code. My knowledge for this is probably not good enough. If anyone has an idea here, hints are welcome. Closing this for now because this seems not to be solvable with javascript / system calls.
