### ISSUE TITLE
Please add info about UEFI vs BIOS, and which device is boot device

### ISSUE THREAD

**Issue by BillDietrich** [sebhildebrandt/systeminformation#304]
Please return info about whether the system firmware supports UEFI or BIOS, and which disk device/partition is the boot device.  Some ways to find out those things are explained in https://itsfoss.com/check-uefi-or-bios/  Thanks.

**Comment by sebhildebrandt** [comment]
@BillDietrich yes, I will add this!

**Comment by sebhildebrandt** [comment]
@BillDietrich Added `uefi` property to `osInfo()` which should be `true` if the OS was booted using UEFI, otherwise `false`. So this is only part of your feature request as it just determine if UEFI was used. I did not found a consistent way to detect if the firmware supports UEFI. Closing it for now.

Version 4.19.0 just released.
