### ISSUE TITLE
Does ischarging on battery info return true when system is 100% charged and the charger is connected.

### ISSUE THREAD

**Issue by ruk-na-Ziddi** [sebhildebrandt/systeminformation#357]
Sorry to add this question in a wrong section as I couldn't see an option for **issue type as question**.

I wanted to understand what is difference between **acconnected** and **ischarging** attributes on battery response?

One difference I can think of is that acconncted returns true even when battery is 100% full and charger is connected but ischarging might return false for the same as battery is already fully charged and not charging? I couldn't verify this scenario as both acconnected and ischarging were returning true for me.

Please, Let me know if my understanding is correct also if there are more differences I would like to understand those as well.

Thanks

**Comment by sebhildebrandt** [comment]
@ruk-na-Ziddi this actually depends on the OS we are talking about. The "discharging" information is determined differently on the different systems as some of them specifically return confirmation if they are charging (independent of the charging level) ... 

So the question is, which OS are you using?

**Comment by ruk-na-Ziddi** [comment]
Hi @sebhildebrandt I'm using windows 10 OS.

**Comment by sebhildebrandt** [comment]
@ruk-na-Ziddi Windows actually gives information if it is charging or not (BatteryStatus). Still, I had to make some calculation because this status depends on the underlying hardware. So here is how I determine if the battery is charging `ischarging`:

IF 
- windows knows, that the system is charging (not supported on all systems) 

OR 

- the windows battery status is NOT "fully charged" AND the windows battery status is NOT "discharging" AND the battery percentage is < 100

THEN I set `ischarging` too true. To my mind this is the most accurate way.

**Comment by ruk-na-Ziddi** [comment]
Awesome @sebhildebrandt That helps a lot.
Just clearing my understanding again, This means if battery status is **Fully charged** then, on windows OS **ischarging** will return false even when charger is connected.

**Comment by sebhildebrandt** [comment]
@ruk-na-Ziddi Correct! Closing this for now, OK?

**Comment by ruk-na-Ziddi** [comment]
Thanks @sebhildebrandt
