### ISSUE TITLE
dockerAll() ends the process when run inside a docker container

### ISSUE THREAD

**Issue by rogierschouten** [sebhildebrandt/systeminformation#396]
**Describe the bug**
Calling `dockerAll()` from within a docker container on docker for Windows will end the process

**To Reproduce**

1. Create the files below
2. Build docker image using `docker build -t systeminfotest .`
3. Run docker container using `docker run systeminfotest`
4. Observe 'started' output but otherwise no output

index.js:
```javascript
const si = require("systeminformation");

(async () => {
	try {
		console.log("started");
		const results = await Promise.all([
			si.dockerAll(), // does not work within docker on windows, crashes the process
		]);
		console.log(JSON.stringify(results, undefined, 2)); // logging never seen
	} catch (error) {
		console.log(error); // logging never seen
	}
})();
```

package.json:
```json
{
  "name": "systeminfotest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "systeminformation": "4.26.10"
  }
}
```

Dockerfile:
```Dockerfile
FROM node:14-alpine

# Install dependencies for node-gyp
RUN apk add --no-cache --virtual .gyp python make g++

# Prepare NPM module
USER node

# Create working directory and ensure that the node user has access;
RUN mkdir -p /home/node/app ; \
    chown -R node:node /home/node/app ;

# cd into working directory
WORKDIR /home/node/app

# Copy package.json first so we don't have to run `npm install` each time when other files change
COPY package.json .
COPY index.js .

# Configure spirit registry and npm install
RUN npm install --no-package-lock --production

CMD node ./index.js
```

**Current Output**

```shell
started
```

**Expected behavior**

```shell
started
<output from dockerAll()>
```

**Environment (please complete the following information):**
 - systeminformation package version: 4.26.10
 - OS: Windows 10
 - Hardware PC
 - Docker: Docker version 19.03.5, build 633a0ea
 - Node: v14.8.0

**Additional context**

Running the same program outside of Docker works fine.

**Comment by sebhildebrandt** [comment]
@rogierschouten will have to test this tomorrow ... thank you for your detailed bug report.

**Comment by rdlowrey** [comment]
@rogierschouten I ran into the same issue.

The root cause is that the docker container itself can't access the docker.sock file without effort on your part. You can [mount the docker.sock file as described here](https://stackoverflow.com/a/33183227/895378). This is probably fine in a local dev environment, but be aware there are potential security issues with this (as outlined in the link).

Doing so in a `docker-compose.yml` would look like:

```
  svc-app:
    image: foo/bar
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**The Problem**

Even though the docker.sock file isn't found, the process shouldn't hang indefinitely.

When docker.sock is missing, [this block gets triggered inside `DockerSocket.listContainers()`](https://github.com/sebhildebrandt/systeminformation/blob/master/lib/dockerSocket.js#L73-L75):

```
      socket.on('error', () => {
        socket = false;
        callback({});
      });
```

[The resulting block in `lib/docker.js`](https://github.com/sebhildebrandt/systeminformation/blob/master/lib/docker.js#L126-L165) then never calls `resolve()` to resolve the promise.

Replacing line 165 in `lib/dockers.js` with the following solves the problem:

```
} else { 
  resolve(result);
}
```

**Comment by rdlowrey** [comment]
PR open to fix at https://github.com/sebhildebrandt/systeminformation/pull/428

**Comment by sebhildebrandt** [comment]
@rdlowrey @rogierschouten Fixed. Version 4.27.10 just published.

**Comment by rdlowrey** [comment]
@sebhildebrandt Thanks for addressing so quickly ❤️. Have a great day!
