### ISSUE TITLE
Which value should I use to measure CPU load and network bandwidth ?

### ISSUE THREAD

**Issue by kietheros** [sebhildebrandt/systeminformation#413]
I'm writing a simple load balancer. I have some nodes (servers), and each node will report cpu load and network bandwidth (my code using module systeminformation) to load balancer. Each node is a streaming service, with average bandwidth 400 -> 500 Mbps. My system is small, a load balancer and 10 streaming nodes.
Which value should I use to measure CPU load and network bandwidth in each node?
1. CPU
 avgload or currentload or os.loadavg()

2. Network bandwith
rx_sec + tx_sec or only tx_sec

**Comment by sebhildebrandt** [comment]
@kietheros I am not sure, what your approach is here and if it would make sense to use these values in a load balancer ... 

I would consider two approaches: 

1. In a load balancer you can determine on parameters that happened right now (so basically in that millisecond or so). `avgload`or `currentload` are not that accurate. So when you get a result, a few milliseconds the situation can be completely different. 

2. Or you would like to make decisions in your load balancer based on more general - average - parameters ... then you can of course use `avgload` or `currentload`. `avgload` is based on what nodejs gives back for the cpu. I created the `currentload()` function because this is the more accurate and you can control it much better. Be sure, that this gives back the real load between two calls of `currentload`. So if you call this every second, it will give you back the load in this past second. 
Concerning network bandwidth. I would - depending on your use case - use both values separately. You probably would like to be in control of received AND send bytes. Depending on the network both could be a bottleneck. But this is for sure much more complex because this would also mean, that you know about the overall bandwidth (read AND write) of the network where your services are hosted. If you e.g. make a load balancing between two machines in one network and the external connection is the bottleneck, your load balancing would be kind of independent of what is going on in one of the two machines. If the bandwidth of machine 1 hits the limits of the external network, then you would also get no gains when you switch to the other machine (behind the same external network). So the network topology would play a rule here also.

So in both cases I am not really sure if your approach really is the best ... 

Hope my explanation make some sense for you. Perhaps you can describe your idea here more detailed.

**Comment by kietheros** [comment]
@sebhildebrandt Thank for your reply !
I have just updated my questions. I think using average load is suitable. After reading your reply, I have a bit of a misunderstanding about load average and cpu utilization. Please correct me if I'm wrong

- currentload: the current cpu utilization, unit: percent

- os.loadavg() or value in htop: load average in last 1, 5 and 15 minutes. I will use **load average / number of cores** to convert to percent.

- avgload: I don't sure about this value. Perhaps like value in htop (load average), measure between 2 calls of this function

About network bandwidth, I will use rx_sec + tx_sec because my node both sends and receives data.

**Comment by sebhildebrandt** [comment]
@kietheros so this is nearly correct ...

- `currentload`: the current cpu utilization, unit: percent ... dependent on calls to this function (as described above)
- `avgload `: this is actually the average of 1, 5 and 15 min **load average / number of cores** ... independent of calls of this function

**Comment by kietheros** [comment]
@sebhildebrandt 
Thank for your reply. I try using two below values:
**currentload**
I save currentload in each second.
value1 = calculate average currentload in last 60s. (%)

**avg**
value2 = avg * 100. (%)

I find that value2 is much larger than value1 (value1 ~ 20 -> 25,  value2 ~ 70). Which value should I use to represent cpu load? Which value does services as HAProxy use ? I'm a newcomer, could you tell me your selection ?

**Comment by sebhildebrandt** [comment]
@kietheros and what is compared to that the first value of os.loadavg() / number of cores?

**Comment by kietheros** [comment]
Result:  systemiformation avgload ~  os.loadavg() / number of cores

**Comment by sebhildebrandt** [comment]
@kietheros how many cores you have and how many threads?

**Comment by kietheros** [comment]
{
 use_average_of_currentload: 23.722149410222805,
  use_avg: 78,
  use_os_loadavg: 78.070068359375 
}

os.cpus().length = 8
(I have checked in htop, 8 cores / 8 threads)

**Comment by kietheros** [comment]
`
const listCpuLoads = [];
si.currentLoad(async (data) => {
            if (listCpuLoads.length >= 60) {
                listCpuLoads.shift();
            }
            listCpuLoads.push(data.currentload);
            results.average_of_currentload = getAverage(listCpuLoads);
            results.avg = data.avgload * 100;
            results.os_loadavg = os.loadavg()[0] / os.cpus().length * 100;
        });
`
`
{
  average_of_currentload: 24.586460869366967,
  avg: 60,
  os_loadavg: 60.009765625 
}
`

**Comment by sebhildebrandt** [comment]
@kietheros so this is absolutely fine!

Pleas consider, that os loading is NOT a percentage value!! It is more about running and waiting threads:

> Linux load averages are "system load averages" that show the running thread (task) demand 
> on the system as an average number of running plus waiting threads. This measures demand, 
> which can be greater than what the system is currently processing

my `currentload`-function on the other hand IS a percentage value! 

So is makes no sense to compare the two values directly.

**Comment by kietheros** [comment]
@sebhildebrandt 
OK. I only consider which value is better for represent the system load. In your opinion, which one is better ?

**Comment by sebhildebrandt** [comment]
@kietheros 

- if you want to make decisions on the true percentage values - go for `currentload`
- if you just want to compare and take the lowest, take `os.loadavg()[0]` as this is probably faster

**Comment by kietheros** [comment]
@sebhildebrandt Thank you very much ! I will use currentload.

**Comment by fabiospampinato** [comment]
> avgload : this is actually the average of 1, 5 and 15 min load average / number of cores ... independent of calls of this function

@sebhildebrandt would it be possible to expose the raw min1 min5 and min15 load numbers too? As far as I can see they are currently not exposed.

**Comment by sebhildebrandt** [comment]
@fabiospampinato that would make sense ... will extend `si.currentLoad()` to provide those values too.

**Comment by sebhildebrandt** [comment]
@fabiospampinato the question here is: would it really make sense 
- to just provide the 1, 5 and 15 min numbers (as given from the OS) which needs extra calculation to give meaningful results 
- or should I provide my post-calculated results (which means already divided by CPU cores) ...
What do you think?

**Comment by fabiospampinato** [comment]
Potentially providing both kind of values could be the optimal option, but for my use case specifically I want to recreate the load sections that tools like top or glances have, for that I think I need the value provided by the OS, I personally don't care too much about the per-core loads (although that could come in handy to me in the future).

**Comment by sebhildebrandt** [comment]
@fabiospampinato 

- the first one (average of 1, 5 and 15 min load average - given by the OS) can be determined directly in nodes with `os.loadavg()` - so for your purposes actually no need to extend systeminformation
- but I will introduce a avgload (levied by cores) because this is - at least to me - more meaningful. 

Explanation: If the avgload given by the OS is high but you have plenty of cores, this might be not a big problem. In relation to just 1 or two cores, this really shows that your system is under pressure.

**Comment by fabiospampinato** [comment]
> os.loadavg()

I wasn't aware that existed, thanks for pointing that out!

That's certainly good enough for me, but I think it would be cleaner if this library provided all that sort of data directly, using multiple libraries to get information about the system like that is kind of ugly.
