### ISSUE TITLE
Hi, this is a great npm library, I have a question Can i Use this library in a API , to get Client system data

### ISSUE THREAD

**Issue by khanakhun** [sebhildebrandt/systeminformation#491]
Hi, Any help would be great and appreciate able, I developing a site where User can Get their all system specification in Just one Click, then I find This amazing library, so My question is that how Can I use this in my website, should I have to make an API for it, will it work that way, e-g I will deploy the API and Whenever a  request is Made will it be able to get the System specification of the system where the Site is opened. Looking forward to an answer

**Comment by sebhildebrandt** [comment]
@khanakhun Hi and thank you for your question. So if I understand this correct: you have clients that call a server (maybe an API on this server) and what you what to achieve is, that the client gets system information data of the CLIENTS system? If this is what you want to achieve, this is not possible. What you CAN achieve, is the you get system information data from the SERVER and send it to the client (I guess this is NOT what you want to do, right?).

Explanation: you can run the code of this library only server side (see also docs systeminformation.io). There is no possibility to run this on client side (within a browser) due to security reasons!

Hope this makes it clear. If I misunderstood your question, can you please clarify your goal. I would be happy to help out.
