### ISSUE TITLE
Is systeminformation can integrated with scanning to network?

### ISSUE THREAD

**Issue by rizkyfaza20** [sebhildebrandt/systeminformation#494]
Hi all,

I'm mostly find this module dependencies by googling after all, and it was great! I found something that I want to build with this module.

But I have problem right now, like I want to integrate this module to network scanner so, the specific IP on network can show the specification of hardware details, then I've been search all of the documentation but i've got nothing. 

Is there any module that can used for scan the network and get the IP, and the IP can be checked for scanning the system information? or maybe I can integrate it with any language e.g Python?

p.s I've been using this dependencies with Python but i've got nothing at all, if u guys can help please can you recommend me what tools or framework that can used for scanning the network and the specific host because i've been looking so hard for this solution.

**Comment by sebhildebrandt** [comment]
@rizkyfaza20 here some comments:

Generally, each system on a network would prohibit to track detailed system information due to security reasons. So there are of course possibilities in a secure network environment (like e.g. wmic on windows would allow to get data also from other computers if authorization is correct). So if you do not have access to the other machines at the network: this should not. be possible!

Of course if your scenario is like this: you have several machines (you are in control of) in your network and have a network scanner in your own network, then you could do something like this: On your clients you set up a service using `systeminformation` library (REST API for instance). As soon as you scanner detects an IP of one of your machines, the scanner requests data from the client and the client then respond with the wanted data. Be sure to protect the API, so that no one else can retrieve your machines data ;-)

Closing this for now.

**Comment by rizkyfaza20** [comment]
Dear Sebastian,

Thank you for your reply, I hope i can implement it very soon.

Best regards,

Rizky Faza


Pada tanggal Sab, 20 Feb 2021 pukul 13.25 Sebastian Hildebrandt <
notifications@github.com> menulis:
