### ISSUE TITLE
await si.processes().running returning 0

### ISSUE THREAD

**Issue by SamHodge07** [sebhildebrandt/systeminformation#515]
Basically, as the title suggest, 
`await si.processes().running` is always returning 0 
However, `await si.processes().all` returns (243) a likely figure.

Additional information:
systeminformation package version: systeminformation@5.6.8 
OS: Windows 10 Home
Hardware: Acer swift laptop

Thanks!

**Comment by sebhildebrandt** [comment]
@SamHodge07 ... unfortunately `status` value in windows process information (`wmic get process`) is always NULL because Microsoft did not implemented this (see also here: https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-process). Therefore I cannot determine the status of a certain process. So what you should see is that `processes().all` is equal to `processes().unknown` and the other ones are 0, right? Seems that I forgot to make this clear in the documentation. Will add notes to the docs soon. Closing this for now.
