### ISSUE TITLE
Windows Intel: sometimes systemInformation.xxxx() never resolve

### ISSUE THREAD

**Issue by ibc** [sebhildebrandt/systeminformation#521]
**Describe the bug**

Maybe related to #407.

This is happening in Electron 11 and Electron 12 in Windows 10 Intel. We use the following calls and sometimes we get a timeout error in our application because some of them never resolves/rejects:

* `await systemInformation.system()`
* `await systemInformation.cpu()`
* `await systemInformation.graphics()`

In fact, in an attempt to mitigate this problem, we call all those methods in parallel using `Promise.all()`, and what we see is that when one of them fail (it never resolves) the others do it as well.

We have been told in https://github.com/sebhildebrandt/systeminformation/issues/407#issuecomment-819377590 that:

> the problem you are describing is due to the fact that windows wmic is super slow!

We wait up to 20 seconds for those calls to resolve.

**To Reproduce**

Hard to provide STR. It just happens from time to time. In our case, it happens specially to Windows Intel users launching our Electron based app for first time.

**Environment (please complete the following information):**
 - systeminformation package version: 5.0.10
 - OS: Windows 10
 - Hardware: N/A

**Comment by sebhildebrandt** [comment]
@ibc can you confirm that they NEVER resolve or is it just to your timeout limitation. As we discussed in an other issue, the time it takes is due to the slow implementation of Windows `WMIC`, and we do not have any control on that.

**Comment by ibc** [comment]
Actually it may be, indeed, that it takes too long (this is: more than 20 seconds in our case).

**Comment by sebhildebrandt** [comment]
@ibc can you provide time/duration examples for each of the three functions?

```
const si = require('systeminformation');

(async() => {
	const startTotalTime = Date.now();
	let startTime = startTotalTime;

	await si.system();
	console.log(`1 system   : ${(Date.now() - startTime) * 0.001} s`); startTime = Date.now();

	await si.cpu();
	console.log(`2 cpu      : ${(Date.now() - startTime) * 0.001} s`); startTime = Date.now();

	await si.graphics();
	console.log(`3 graphics : ${(Date.now() - startTime) * 0.001} s`);

	const endTotalTime = Date.now();
	console.log(`Total time : ${(endTotalTime - startTotalTime) * 0.001} s`);
})();
```

**Comment by ibc** [comment]
I'll try by asking people. I don't use Windows.

**Comment by sebhildebrandt** [comment]
@ibc here some values from one of my low mid range machines (just as a reference):

Running on Windows 10, Intel Core™ i5-5200U, 2 Cores, 8GB (low mid range machine from 2015) - right after booting the machine:

C:\>node index.js
1 system   : 0.531 s
2 cpu      : 4.031 s
3 graphics : 3.0620000000000003 s
Total time : 7.639 s

C:\>node index.js
1 system   : 0.551 s
2 cpu      : 3.4130000000000003 s
3 graphics : 1.953 s
Total time : 5.949 s

C:\>node index.js
1 system   : 0.499 s
2 cpu      : 3.454 s
3 graphics : 1.938 s
Total time : 5.906 s

**Comment by sebhildebrandt** [comment]
@ibc :

So when running this in parallel, like so:

```
const si = require('systeminformation');

const startTotalTime = Date.now();

Promise.all([
  si.system(),
  si.cpu(),
  si.graphics()
]).then(res => {
  const endTotalTime = Date.now();
  console.log(`Total time : ${(endTotalTime - startTotalTime) * 0.001} s`);
});
```

... this gives me the following result:

```
C:\>node parallel.js
Total time : 4.1930000000000005 s
```

And unfortunalety, this is due to the slow implementation of Microsofts `WMIC` ... so I would not really consider this as an `systeminformation` issue.

**Comment by sebhildebrandt** [comment]
@ibc is there any link to the specific electron app you are talking about? Just curious

**Comment by ibc** [comment]
@sebhildebrandt sorry for the delay. We are not using this collected data to fill any UI. The Electron app we are using is private so cannot share. However we don't do anything special but just call `systemInformation.system()` and `systemInformation.graphics()` within a `Promise.all()`.

My colleagues using Windows are gonna try you code above and paste output here today.

**Comment by ArcanisCz** [comment]
Hi there! @ibc colleague with windows here.
(Windows 10, ntel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz, Nvidia GeForce  RTX 2070)
Calling above mentioned codes in our electron folder

##  Sequential results:

```
1 system   : 0.209 s
2 cpu      : 2.6870000000000003 s
3 graphics : 0.687 s
Total time : 3.583 s

1 system   : 0.201 s
2 cpu      : 2.611 s
3 graphics : 0.577 s
Total time : 3.39 s

1 system   : 0.195 s
2 cpu      : 2.58 s
3 graphics : 0.583 s
Total time : 3.358 s
```

## Parallel results 
`Total time : 3.1790000000000003 s`

**Comment by ArcanisCz** [comment]
First call after boot
```
1 system   : 0.392 s
2 cpu      : 2.923 s
3 graphics : 0.807 s
Total time : 4.122 s
```

**Comment by sebhildebrandt** [comment]
@ibc: Seems, that the issues (not returning within your 20 secs) is 

- only occasionally - as your examples showed, we have 3-7 secs overall for all three functions sequentially (and max 4 when run in parallel)
- most probably due to si.cpu() - which takes the most time to return results here.

In my code I do see one parcel call that can really take longer ... I am currently investigating if I can get this partial information also with a different call (that could then be faster).

**Comment by ibc** [comment]
Thanks a lot @sebhildebrandt

**Comment by sebhildebrandt** [comment]
@ibc changed the way to get `virtualization` and `hypervisor` information for windows. This improves the runtime of `si.cpu()` a little bit ... but do not expect too much. Closing this for now, as we already seen that the called functions resolves according to all our tests but on some low-end machines this might be slow (due to the underlying windows system calls).

**Comment by ibc** [comment]
Thanks @sebhildebrandt, it makes sense.

**Comment by thorsent** [comment]
Closed topic but worth noting for future head scratchers that WMIC.exe is on Microsoft's recommended block list due to it being an attack vector. We've experienced environments where these calls fail to return entirely because WMIC is blocked. We've also experienced environments where these calls seem to be slowed down presumably by Windows Defender or other security systems:

https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-block-rules

**Comment by ibc** [comment]
Thanks a lot @sebhildebrandt
