### ISSUE TITLE
AMD GPU temperature is not shown

### ISSUE THREAD

**Issue by vahidbabaveisi** [sebhildebrandt/systeminformation#522]
Hi,

I use system information in nodejs but when I tested it on AMD RX580 GPUs, I received no temperature in controllers JSON. Can you help me?

I use windows 10. All of drivers including Adrenalin (AMD) are installed.

Thanks.

**Comment by sebhildebrandt** [comment]
@vahidbabaveisi currently - especially on windows - we cannot determine all GPU details for all hardware platforms. For Nvidia we have a solution in place but for AMD this is still missing. so I have two questions:

- can you provide the full output (as text) of `si.graphics()` on your machine so that I can see what we got here and what is missing.
- if you hava any idea to get more detailed status information of a AMD GPU from command line, can you give me a hint and maybe also example output? Than I might be able to implement this also for AMD graphic cards.

**Comment by vahidbabaveisi** [comment]
Thanks, this is the output:

"{"title":"GPU","message":{"controllers":[{"vendor":"Amyuni","model":"USB Mobile Monitor Virtual Display","bus":"","vram":0,"vramDynamic":true,"subDeviceId":null},{"vendor":"Advanced Micro Devices, Inc.","model":"Radeon RX 580 Series","bus":"PCI","vram":4095,"vramDynamic":true,"subDeviceId":"C5801682"},{"vendor":"Advanced Micro Devices, Inc.","model":"Radeon RX 580 Series","bus":"PCI","vram":4095,"vramDynamic":true,"subDeviceId":"C5801682"},{"vendor":"Advanced Micro Devices, Inc.","model":"Radeon RX 580 Series","bus":"PCI","vram":4095,"vramDynamic":true,"subDeviceId":"C5801682"}],"displays":[{"vendor":"(Standard monitor types)","model":"Generic PnP Monitor","deviceName":"\\\\.\\DISPLAY25","main":true,"builtin":false,"connection":"HDMI","resolutionX":640,"resolutionY":480,"sizeX":1,"sizeY":0,"pixelDepth":32,"currentResX":1920,"currentResY":1080,"positionX":0,"positionY":0,"currentRefreshRate":59}]}}"

**Comment by sebhildebrandt** [comment]
@vahidbabaveisi OK, as we see, there is not that detailed information like on machines with Nvidia GPUs (here we have `nvidia-smi` to determine more detailed information). As I am not aware of any method to get detailed information for AMD GPUs on windows from the command line, I am currently not able to provide a solution. I will keep an eye on that but closing this issue for now. If you have any idea here, just give me a hint.
