### ISSUE TITLE
Port 3000 ?!

### ISSUE THREAD

**Issue by jchisholm59** [sebhildebrandt/systeminformation#648]
Probably just me being stoopid but why on earth would these scripts configured to try to listen on port 3000, when that's the port that Grafana uses?

**Comment by sebhildebrandt** [comment]
@jchisholm59 this is interesting ... so let me explain, why I think, this is not related to this package:

- `systeminformation` does not spin up any http server and is not listening to any port
- you cannot find any `createServer` or any similar thing in the code of this package
- the only situation where `http` is used in this library (windows only - just a get request) is when calling `inetChecksite()` to check if a certain internet site is reachable. You need to call this function explicitly to have this situation
- `systeminformation` does not have any external dependencies so I do not see any other way that malicious code would spin up a server due to this library.

Can you please provide more information about the context in which you are using the package?

- OS and OS version
- `systeminformation` package version
- code snippets on how you are using the library
- more about the code environment how the library is used
- maybe also package.jason of the project where you are discovering this behaviour

Best regards

**Comment by sebhildebrandt** [comment]
Closing this for now as I do not think that this is related to this package. If anyone is having trouble with the same issue please reopen this one.
