### ISSUE TITLE
Computer load extremely high when loading data

### ISSUE THREAD

**Issue by binse03** [sebhildebrandt/systeminformation#743]
Hi, 

my cpu usage in task manager (windows) goes to 100% every time i run this interval. So my computer is getting extremely slow. Is it because the module eats up too much computerpower or my CPU is just too bad?
Incidentally, I write the array in a .json. But that shouldn't be this extreme load on my computer. If i make the interval faster my computer crashes. (just tested with 1000ms)

What am I doing wrong or maybe the module is broken?

<pre><code>const si = require('systeminformation');
valueObject = {
  osInfo: 'distro, serial, hostname, uefi',
  users: 'user',
  graphics: 'controllers, model, vram, memoryTotal, memoryUsed, temperatureGpu, fanSpeed, bus',
  cpu: 'manufacturer, brand, cores, physicalCores, speedMax',
  cpuCurrentSpeed: 'avg',
  diskLayout: 'name, vendor, type, size',
  fsSize: 'used',
  mem: 'total, used',
  memLayout: 'clockSpeed, type, manufacturer',
  wifiNetworks: 'ssid, quality, securtiy',
  system: 'manufacturer, model, serial, virtual',
  bios: 'version',
  networkInterfaces: 'dnsSuffix, speed, iface, ip4, mac',
  inetChecksite: '(https://www.google.com/) ok',
  battery: 'hasBattery, isCharging, percent, timeRemaining, type, manufacturer'
}

setInterval(function() {
  si.get(valueObject).then(data => {
    require('fs').writeFile(
      'synced_data.json',
      JSON.stringify(data),
      function (err) {
          if (err) {
              console.error('oh shit - not good');
          }
      }
    );
  });
  var date =  new Date().toLocaleTimeString('en-US', { hour12: false, 
    hour: "numeric", 
    minute: "numeric",
    second: "numeric"});
  console.log("last sync at " + date);
}, 5000)
</code></pre>

my CPU is a Intel Core i7-3770 @ 3.40GHz

**Comment by sebhildebrandt** [comment]
@binse03 ... two remarks here:

- in this module we rely on information we can get fron the OS by calling build in functionality. I assume (maybe I am wrong) that you are working on a windows machine. Here the problem is, that windows is really not efficient in providing system information data (like e.g. linux). If this is the case, you can only extend your interval. Nothing we can do on our side to improve it.
- having a look at your json: I would split this up into two parts: the first one would be "static" data like osInfo, cpu, diskLayout, memLayout, bios, etc... so basically everything that do not change every 5 seconds. The second part would then be the dynamic one. Also here you might split this up. E.g. `graphics` is quite time consuming and therefore should be called not that often. 

Hope this will help improving your project.
