### ISSUE TITLE
Not getting the users hardware info

### ISSUE THREAD

**Issue by vladikdx** [sebhildebrandt/systeminformation#849]
Hi, I am using the library in my MERN app, the library is running on the server and the app is deployed already.
I have only one issue, when fetching the data from the server I am getting the hardware info of the deployed server itself, I an interested in getting the hardware info of the user. am I missing something? what purpose of the app is getting the details of the server? for what?

Thanks.

**Comment by sebhildebrandt** [comment]
@vladikdx ... based on the information that you gave me, I can only guess about your scenario:

- you have something like a server app (Nodejs, Express), which uses `systeminformation`?
- users are then accessing this remotely?  (some sort of API)
- users are accessing it through a browser? (React App?)
- and then you expect that they would see the hardware data of their local machines?

Well there are several reasons why this would never work:

- `systeminformation` is a nodejs library, that needs to run in a `nodejs` environment and it gets the data of the machine where it runs. This is intentional! So if if runs on a server, you geht the data of this server. I am using it to monitor my servers. If you want data from a client machine, you need to run this package in `nodejs` on the client machine. 
- if any web-browser is involved, there are security reasons why (when running javascript code inside a browser) you cannot get detailed information from the client machine. Hackers would love to get such information but - as said - for security reasons this is not possible. Therefore this package is not intended to be used as a JS library inside a browser.
- if - in your scenario - users make an API request to the server (where the systeminformation package is installed) and there on the server you run some `nodejs` code, how should this retrieve any hardware information from the client?? 

I think you need to rethink the concept and idea of your application again. 

Regards. Closing it for now. If I misunderstood something, please feel free to add additional information here.
