### ISSUE TITLE
Deprecated API in Node.js 22+

### ISSUE THREAD

**Issue by toast-ts** [sebhildebrandt/systeminformation#908]
**Is your feature request related to a problem? Please describe.**
When I updated my Node.js to 22.0.0, I have now received a deprecation warning for `util._extend`,
as this is something they deprecated several versions back but only seen the warning in Node22 and not the versions below it like Node21 doesn't seem to display it.

```
(node:35) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Describe the solution you'd like**
Replace the `util._extend` usage with `Object.assign()`, this is located in `lib/util.js` for 3 lines containing this.

**Describe alternatives you've considered**
I have not thought of an alternative solution nor have I allocated my spare time to solve this myself.

**Additional context**
N/A.

**Comment by sebhildebrandt** [comment]
@toast-ts Ok, I will have a look at it ... I have to check also if the alternative would work back also in Node 4.0 as this is the oldest supported version of this library. Otherwise it would be a breaking change witch would then require a major version change ... I am already working intensively on a fully rewritten version 6.0 (written in TypeScript).

**Comment by sebhildebrandt** [comment]
@toast-ts ... Ok I fixed it ... version 5.22.8 just published. Can you check it on your side?

**Comment by toast-ts** [comment]
Yes, it is fixed, no deprecation warning in console.
Thank you.
